# Generated by Django 3.1.4 on 2020-12-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Cancha')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telephone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDuration',
            fields=[
                ('duration_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField(verbose_name='Duracion')),
            ],
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('start_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.court', verbose_name='Cancha')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.customer', verbose_name='Cliente')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.matchduration', verbose_name='Duracion')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.starttime', verbose_name='Hora de Inicio')),
            ],
        ),
    ]
