# Generated by Django 3.1.4 on 2021-01-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedReservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha Fija')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.court', verbose_name='Cancha')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.customer', verbose_name='Cliente')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.matchduration', verbose_name='Duracion')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.starttime', verbose_name='Hora de Inicio')),
            ],
        ),
    ]
