# Generated by Django 3.1.4 on 2021-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_fixedreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedreservation',
            old_name='court',
            new_name='fixed_court',
        ),
        migrations.AlterField(
            model_name='fixedreservation',
            name='date',
            field=models.CharField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], max_length=15, null=True, verbose_name='Fecha Fija'),
        ),
    ]
