# Generated by Django 3.1.4 on 2021-01-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210112_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedreservation',
            old_name='date',
            new_name='fixed_date',
        ),
    ]
