# Generated by Django 3.1.4 on 2021-01-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210112_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedreservation',
            old_name='customer',
            new_name='fixed_customer',
        ),
    ]
